# ── fetch: Startup Splash ──
# Author: Shreyas Ugemuge
#
# A personalized system splash screen on every interactive shell open.
# ASCII art + system stats side-by-side. Fast — no network calls.
#
# Aesthetic: muted labels, meaningful values, personality.
#
# Performance: hardware info cached until reboot, package count cached 1h,
# git streak cached 5m. Cache at ~/.cache/zsh/sysinfo_cache.

# Only run in interactive shells
[[ ! -o interactive ]] && return 0

# ── Colors ──
_D='\033[0;90m'     # dim gray (labels, art)
_A='\033[0;33m'     # yellow (accent — matches prompt face)
_N='\033[0m'        # reset

# ── Cache setup ──
_SI_CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/sysinfo_cache"
[[ -d "${_SI_CACHE:h}" ]] || mkdir -p "${_SI_CACHE:h}"
_SI_DIRTY=0

# Source existing cache (sets _CACHED_* variables)
# shellcheck disable=SC1090
# Dynamic path: cache file generated by this script
[[ -f "$_SI_CACHE" ]] && source "$_SI_CACHE"

# ── Determine current boot time ──
_si_cur_boot=""
if $IS_MACOS; then
    _si_cur_boot="$(sysctl -n kern.boottime 2>/dev/null | awk '{print $4}' | tr -d ',')"
elif $IS_LINUX; then
    _si_cur_boot="$(awk '/btime/{print $2}' /proc/stat 2>/dev/null)"
fi

# ── Hardware info (cached until reboot) ──
_f_host=""
_f_os=""
_f_cpu=""
_f_gpu=""
_f_ram=""

if [[ "$_si_cur_boot" != "$_CACHED_BOOT_TIME" ]] || [[ -z "$_CACHED_HOST" ]]; then
    # Cache miss — recompute hardware info
    if $IS_MACOS; then
        _f_host="$(scutil --get ComputerName 2>/dev/null || hostname -s)"
        _f_os="macOS $(sw_vers -productVersion 2>/dev/null) ($(uname -m))"
        _f_cpu="$(sysctl -n machdep.cpu.brand_string 2>/dev/null)"
        _f_gpu="$(system_profiler SPDisplaysDataType 2>/dev/null | awk -F': ' '/Chipset Model|Chip:/{print $2; exit}')"
        _f_ram="$(( $(sysctl -n hw.memsize 2>/dev/null) / 1073741824 )) GB"
    elif $IS_LINUX; then
        _f_host="$(hostname -s 2>/dev/null)"
        if [[ -f /etc/os-release ]]; then
            # shellcheck disable=SC1091
            # /etc/os-release is a standard Linux file; not available at shellcheck analysis time
            _f_os="$(. /etc/os-release && echo "$PRETTY_NAME") ($(uname -m))"
        else
            _f_os="Linux $(uname -r) ($(uname -m))"
        fi
        _f_cpu="$(awk -F': ' '/model name/{print $2; exit}' /proc/cpuinfo 2>/dev/null)"
        _f_gpu="$(lspci 2>/dev/null | awk -F': ' '/VGA|3D/{print $2; exit}')"
        _f_ram="$(awk '/MemTotal/{printf "%.0f GB", $2/1048576}' /proc/meminfo 2>/dev/null)"
    fi
    _CACHED_BOOT_TIME="$_si_cur_boot"
    _CACHED_HOST="$_f_host"
    _CACHED_OS="$_f_os"
    _CACHED_CPU="$_f_cpu"
    _CACHED_GPU="$_f_gpu"
    _CACHED_RAM="$_f_ram"
    _SI_DIRTY=1
else
    # Cache hit — use stored values
    _f_host="$_CACHED_HOST"
    _f_os="$_CACHED_OS"
    _f_cpu="$_CACHED_CPU"
    _f_gpu="$_CACHED_GPU"
    _f_ram="$_CACHED_RAM"
fi

# ── Uptime (always live — pure arithmetic, ~1ms) ──
_f_uptime=""
if $IS_MACOS; then
    if [[ -n "$_si_cur_boot" ]]; then
        _f_now="$(date +%s)"
        _f_secs=$(( _f_now - _si_cur_boot ))
        _f_days=$(( _f_secs / 86400 ))
        _f_hours=$(( (_f_secs % 86400) / 3600 ))
        _f_mins=$(( (_f_secs % 3600) / 60 ))
        if (( _f_days > 0 )); then
            _f_uptime="${_f_days}d ${_f_hours}h ${_f_mins}m"
        elif (( _f_hours > 0 )); then
            _f_uptime="${_f_hours}h ${_f_mins}m"
        else
            _f_uptime="${_f_mins}m"
        fi
        unset _f_now _f_secs _f_days _f_hours _f_mins
    fi
elif $IS_LINUX; then
    _f_uptime="$(uptime -p 2>/dev/null | sed 's/up //' || uptime | awk -F'up ' '{print $2}' | awk -F',' '{print $1}')"
fi

# ── Shell version (fast, no cache needed) ──
_f_shell="zsh ${ZSH_VERSION}"

# ── Package count (1 hour TTL) ──
_f_packages=""
_si_now="$(date +%s)"
if [[ -n "$_CACHED_PKG_STAMP" ]] && (( _si_now - _CACHED_PKG_STAMP < 3600 )); then
    _f_packages="$_CACHED_PKG_COUNT"
else
    if $IS_MACOS; then
        if command -v brew &>/dev/null; then
            _f_brew="$(brew list --formula 2>/dev/null | wc -l | tr -d ' ')"
            _f_packages="${_f_brew} (brew)"
            unset _f_brew
        fi
    elif $IS_LINUX; then
        if command -v apt &>/dev/null; then
            _f_packages="$(dpkg --list 2>/dev/null | grep -c '^ii') (apt)"
        elif command -v brew &>/dev/null; then
            _f_packages="$(brew list --formula 2>/dev/null | wc -l | tr -d ' ') (brew)"
        elif command -v pacman &>/dev/null; then
            _f_packages="$(pacman -Q 2>/dev/null | wc -l | tr -d ' ') (pacman)"
        fi
    fi
    _CACHED_PKG_COUNT="$_f_packages"
    _CACHED_PKG_STAMP="$_si_now"
    _SI_DIRTY=1
fi

# ── Git streak (5 minute TTL, guarded by $HOME/.git) ──
_f_streak=""
if command -v git &>/dev/null && [[ -d "$HOME/.git" ]]; then
    if [[ -n "$_CACHED_STREAK_STAMP" ]] && (( _si_now - _CACHED_STREAK_STAMP < 300 )); then
        _f_streak="$_CACHED_STREAK"
    else
        _f_today_commits="$(git -C "$HOME" log --all --oneline --since='midnight' --author="$(git config user.name 2>/dev/null)" 2>/dev/null | wc -l | tr -d ' ')"
        if [[ "$_f_today_commits" -gt 0 ]] 2>/dev/null; then
            _f_streak="${_f_today_commits} today"
        fi
        unset _f_today_commits
        _CACHED_STREAK="$_f_streak"
        _CACHED_STREAK_STAMP="$_si_now"
        _SI_DIRTY=1
    fi
fi

# ── Write cache if anything changed ──
if (( _SI_DIRTY )); then
    cat > "$_SI_CACHE" <<EOF
_CACHED_BOOT_TIME=${(qq)_CACHED_BOOT_TIME}
_CACHED_HOST=${(qq)_CACHED_HOST}
_CACHED_OS=${(qq)_CACHED_OS}
_CACHED_CPU=${(qq)_CACHED_CPU}
_CACHED_GPU=${(qq)_CACHED_GPU}
_CACHED_RAM=${(qq)_CACHED_RAM}
_CACHED_PKG_COUNT=${(qq)_CACHED_PKG_COUNT}
_CACHED_PKG_STAMP=${(qq)_CACHED_PKG_STAMP}
_CACHED_STREAK=${(qq)_CACHED_STREAK}
_CACHED_STREAK_STAMP=${(qq)_CACHED_STREAK_STAMP}
EOF
fi
unset _SI_CACHE _SI_DIRTY _si_cur_boot _si_now
unset _CACHED_BOOT_TIME _CACHED_HOST _CACHED_OS _CACHED_CPU _CACHED_GPU _CACHED_RAM
unset _CACHED_PKG_COUNT _CACHED_PKG_STAMP _CACHED_STREAK _CACHED_STREAK_STAMP

# ── Fortune / quote (if available, keep it short) ──
_f_quote=""
if command -v fortune &>/dev/null; then
    _f_quote="$(fortune -s 2>/dev/null | head -2)"
fi

# ── ASCII art — randomized from a small set ──
# Kept compact (8 lines tall) so it doesn't eat the terminal
_f_art_index=$(( RANDOM % 4 ))

case $_f_art_index in
    0)
_f_art=(
"    ${_A}    ╱╲${_N}"
"    ${_A}   ╱  ╲${_N}"
"    ${_A}  ╱    ╲${_N}"
"    ${_A} ╱──────╲${_N}"
"    ${_A}╱   ${_D}◉  ◉${_A}  ╲${_N}"
"    ${_A}╲   ${_D} ‿‿ ${_A}  ╱${_N}"
"    ${_A} ╲──────╱${_N}"
"    ${_A}  ╲    ╱${_N}"
) ;;
    1)
_f_art=(
"    ${_D}┌─────────┐${_N}"
"    ${_D}│${_A} ◖     ◗ ${_D}│${_N}"
"    ${_D}│${_A}    ▽    ${_D}│${_N}"
"    ${_D}│${_A}  ╰───╯  ${_D}│${_N}"
"    ${_D}├─────────┤${_N}"
"    ${_D}│ ${_N}>${_D}_${_N}<     ${_D}│${_N}"
"    ${_D}│         │${_N}"
"    ${_D}└─────────┘${_N}"
) ;;
    2)
_f_art=(
"    ${_D}    ┏━━━┓${_N}"
"    ${_D}  ┏━┛   ┗━┓${_N}"
"    ${_D}  ┃ ${_A}●   ● ${_D}┃${_N}"
"    ${_D}  ┃ ${_A}  ▼   ${_D}┃${_N}"
"    ${_D}  ┃ ${_A} ───  ${_D}┃${_N}"
"    ${_D}  ┗━┓   ┏━┛${_N}"
"    ${_D}    ┗━━━┛${_N}"
"    ${_D}   ╱     ╲${_N}"
) ;;
    3)
_f_art=(
"    ${_D}  ╭───────╮${_N}"
"    ${_D}  │ ${_A}◉${_D}   ${_A}◉${_D} │${_N}"
"    ${_D}  │ ${_A} ╶─╴ ${_D} │${_N}"
"    ${_D}  ╰───┬───╯${_N}"
"    ${_D}    ╭─┴─╮${_N}"
"    ${_D}   ╱│   │╲${_N}"
"    ${_D}    │   │${_N}"
"    ${_D}    ╰───╯${_N}"
) ;;
esac

# ── Build the stats column ──
_f_stats=()
_f_stats+=("${_A}${_f_host}${_N}")
_f_stats+=("${_D}os${_N}       ${_f_os}")
_f_stats+=("${_D}cpu${_N}      ${_f_cpu}")
[[ -n "$_f_gpu" ]] && _f_stats+=("${_D}gpu${_N}      ${_f_gpu}")
_f_stats+=("${_D}ram${_N}      ${_f_ram}")
_f_stats+=("${_D}uptime${_N}   ${_f_uptime}")
_f_stats+=("${_D}shell${_N}    ${_f_shell}")
[[ -n "$_f_packages" ]] && _f_stats+=("${_D}packages${_N} ${_f_packages}")
[[ -n "$_f_streak" ]] && _f_stats+=("${_D}commits${_N}  ${_f_streak}")

# ── Render side-by-side ──
echo ""
_f_lines=$(( ${#_f_art[@]} > ${#_f_stats[@]} ? ${#_f_art[@]} : ${#_f_stats[@]} ))
for (( i=1; i<=_f_lines; i++ )); do
    _f_left="${_f_art[$i]:-}"
    _f_right="${_f_stats[$i]:-}"
    # Pad art column to ~20 visible chars (art is ~18 + escape codes)
    printf "%b  %b\n" "${_f_left}" "${_f_right}"
done

# ── Quote (below the card) ──
if [[ -n "$_f_quote" ]]; then
    echo ""
    echo -e "    ${_D}${_f_quote}${_N}"
fi

echo ""

# ── Cleanup ──
unset _D _A _N
unset _f_host _f_os _f_cpu _f_gpu _f_ram _f_uptime _f_shell _f_brew _f_packages
unset _f_streak _f_quote _f_art _f_art_index _f_stats _f_lines _f_left _f_right
